// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise'
import { OpenAPI } from './core/OpenAPI'
import { request as __request } from './core/request'
import type {
	HealthcheckResponse,
	HeroesReadHeroByNameData,
	HeroesReadHeroByNameResponse,
	HeroesReadHeroesResponse,
	HeroesReadHeroItemsData,
	HeroesReadHeroItemsResponse,
} from './types.gen'

export class DefaultService {
	/**
	 * Healthcheck
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static healthcheck(): CancelablePromise<HealthcheckResponse> {
		return __request(OpenAPI, {
			method: 'GET',
			url: '/api/v1/healthcheck',
		})
	}
}

export class HeroesService {
	/**
	 * Read Heroes
	 * Get the list of heroes.
	 * @returns HeroesOut Successful Response
	 * @throws ApiError
	 */
	public static readHeroes(): CancelablePromise<HeroesReadHeroesResponse> {
		return __request(OpenAPI, {
			method: 'GET',
			url: '/api/v1/heroes/',
		})
	}

	/**
	 * Read Hero Items
	 * Get the items for a specific hero and position.
	 * @param data The data for the request.
	 * @param data.heroId
	 * @param data.position
	 * @param data.days
	 * @returns HeroItemsOut Successful Response
	 * @throws ApiError
	 */
	public static readHeroItems(
		data: HeroesReadHeroItemsData
	): CancelablePromise<HeroesReadHeroItemsResponse> {
		return __request(OpenAPI, {
			method: 'GET',
			url: '/api/v1/heroes/items',
			query: {
				hero_id: data.heroId,
				position: data.position,
				days: data.days,
			},
			errors: {
				422: 'Validation Error',
			},
		})
	}

	/**
	 * Read Hero By Name
	 * Get the hero by NPC name.
	 * @param data The data for the request.
	 * @param data.name
	 * @returns HeroOut Successful Response
	 * @throws ApiError
	 */
	public static readHeroByName(
		data: HeroesReadHeroByNameData
	): CancelablePromise<HeroesReadHeroByNameResponse> {
		return __request(OpenAPI, {
			method: 'GET',
			url: '/api/v1/heroes/{name}',
			path: {
				name: data.name,
			},
			errors: {
				422: 'Validation Error',
			},
		})
	}
}
