// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthcheckResponse, HeroesGetHeroesResponse } from './types.gen';

export class DefaultService {
    /**
     * Healthcheck
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthcheck(): CancelablePromise<HealthcheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/healthcheck'
        });
    }
    
}

export class HeroesService {
    /**
     * Get Heroes
     * Get the list of heroes.
     * @returns HeroesOut Successful Response
     * @throws ApiError
     */
    public static getHeroes(): CancelablePromise<HeroesGetHeroesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/heroes/'
        });
    }
    
}