// This file is auto-generated by @hey-api/openapi-ts

export type FacetItemStat = {
	facet_id: number
	facet_name: string
	facet_background?: string | null
	facet_icon?: string | null
	items: Array<ItemStat>
}

export type HeroesOut = {
	data: Array<HeroOut>
	count: number
}

export type HeroItemsOut = {
	hero_id: number
	hero_name: string
	hero_npc: string
	facets: Array<FacetItemStat>
}

export type HeroOut = {
	name: string
	npc: string
	hero_id: number
	primary_attribute: PrimaryAttribute
	all_elo?: number | null
	all_matches?: number
	all_winrate?: number
	pos_1?: PositionStats
	pos_2?: PositionStats
	pos_3?: PositionStats
	pos_4?: PositionStats
	pos_5?: PositionStats
}

export type HTTPValidationError = {
	detail?: Array<ValidationError>
}

export type ItemStat = {
	item_id: number
	item_name: string
	category: string
	matches: number
	wins: string
	avg_purchase_time: number
	std_purchase_time: number
	earliest_purchase: number
	latest_purchase: number
	purchases_in_longer_matches: string
	win_rate: number
	purchase_rate: number
	relative_purchase_rate: number
}

export type PositionStats = {
	elo?: number | null
	matches?: number
	winrate?: number
}

export type PrimaryAttribute = 0 | 1 | 2 | 3

export type ValidationError = {
	loc: Array<string | number>
	msg: string
	type: string
}

export type HealthcheckResponse = unknown

export type HeroesReadHeroesResponse = HeroesOut

export type HeroesReadHeroItemsData = {
	days?: number
	heroId: number
	position: string
}

export type HeroesReadHeroItemsResponse = HeroItemsOut

export type HeroesReadHeroByNameData = {
	name: string
}

export type HeroesReadHeroByNameResponse = HeroOut
