// This file is auto-generated by @hey-api/openapi-ts

export type HeroesOut = {
	data: Array<HeroOut>
	count: number
}

export type HeroOut = {
	name: string
	npc: string
	hero_id: number
	primary_attribute: PrimaryAttribute
	all_elo?: number | null
	all_matches?: number
	all_winrate?: number
	pos_1?: PositionStats
	pos_2?: PositionStats
	pos_3?: PositionStats
	pos_4?: PositionStats
	pos_5?: PositionStats
}

export type PositionStats = {
	elo?: number | null
	matches?: number
	winrate?: number
}

export type PrimaryAttribute = 0 | 1 | 2 | 3

export type HealthcheckResponse = unknown

export type HeroesGetHeroesResponse = HeroesOut
